#!/bin/sh

# Gradle start up script for POSIX generated by Gradle.
#
# Important for running:
#
# (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#     noncompliant, but you have some other compliant shell such as ksh or
#     bash, then to run this script, type that shell name before the whole
#     command line, like:
#
#         ksh Gradle start up script
#     or
#         bash Gradle start up script
#
# (2) The Gradle wrapper includes a small stub script that performs the main
#     task, but you probably want to run the main Gradle script instead.
#     That main script invokes the Gradle command with the Gradle wrapper's
#     arguments.
#
# You can further customize startup performance by using the Gradle
# "wrapper" task. For more details see:
# https://docs.gradle.org/current/userguide/gradle_wrapper.html
#
# Uncomment those lines below to set Java home to use a certain JDK.
# JAVA_HOME="/path/to/java" \
#
# Uncomment those lines below to set Java options (note -Xmx should be last, as the space
# is used as a delimiter).
# DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"
#

JARWRAPPER_JAR="gradle/wrapper/gradle-wrapper.jar"

if [ -z "$JAVA_HOME" ] ; then
    JAVA_CMD="java"
else
    JAVA_CMD="$JAVA_HOME/bin/java"
fi

# Determine the Java version
if ! command -v $JAVA_CMD &> /dev/null; then
    echo "Error: JAVA_CMD=$JAVA_CMD could not be found in your PATH." >&2
    exit 1
fi

# transitive the command and its args
exec "$JAVA_CMD" $DEFAULT_JVM_OPTS -cp "$JARWRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
